apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: monitoring
    namespace: flux-system
spec:
    targetNamespace: monitoring
    releaseName: monitoring
    interval: 5m
    chart:
        spec:
            chart: ./charts/monitoring
            sourceRef:
                kind: GitRepository
                name: charts
                namespace: flux-system
    install:
        remediation:
            retries: 3
