apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
    name: charts
    namespace: flux-system
spec:
    interval: 1m
    ref:
        branch: flux
    secretRef:
        name: flux-system
    url: ssh://git@github.com/tiberiu-matei/ops
    ignore: |
        /*
        !/charts/
