apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
    name: charts
    namespace: flux-system
spec:
    interval: 1m
    ref:
        branch: main
    secretRef:
        name: flux-system
    url: https://github.com/tiberiu-matei/ops.git
    ignore: |
        /*
        !/charts/
