apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt
    namespace: cert-manager
spec:
    acme:
        email: tibi.matei02@gmail.com
        privateKeySecretRef:
            name: letsencrypt
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                  cloudflare:
                      apiTokenSecretRef:
                          name: cloudflare-token-secret
                          key: cloudflare-token
            #   selector:
            #       dnsZones:
            #           - "home.investager.com"
