apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: longhorn
    namespace: longhorn
spec:
    secretName: longhorn-tls
    issuerRef:
        name: letsencrypt
        kind: ClusterIssuer
