---
apiVersion: v1
kind: Namespace
metadata:
    name: longhorn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: longhorn
    namespace: longhorn
spec:
    targetNamespace: longhorn
    releaseName: longhorn
    chart:
        spec:
            chart: longhorn
            sourceRef:
                kind: HelmRepository
                name: longhorn
                namespace: flux-system
            version: "1.4.0"
    interval: 1h0m0s
    values:
        defaultSettings:
            deletingConfirmationFlag: "true"
        longhornUI:
            replicas: 1
        longhornConversionWebhook:
            replicas: 1
        longhornAdmissionWebhook:
            replicas: 1
        longhornRecoveryBackend:
            replicas: 1
        ingress:
            enabled: false
        persistence:
            defaultClassReplicaCount: 1
    install:
        crds: CreateReplace
        disableWait: true
    upgrade:
        crds: CreateReplace
        disableWait: true
