---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: sealed-secrets
    namespace: flux-system
spec:
    interval: 1h0m0s
    url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: sealed-secrets
    namespace: flux-system
spec:
    releaseName: sealed-secrets-controller
    targetNamespace: flux-system
    chart:
        spec:
            chart: sealed-secrets
            sourceRef:
                kind: HelmRepository
                name: sealed-secrets
            version: "2.7.3"
    interval: 1h0m0s
    install:
        crds: CreateReplace
    upgrade:
        crds: CreateReplace
