apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
spec:
    encryptedData:
        cloudflare-token: AgBVbmbzj7Qt3Zf39Io9sCinacRj0bHhkisLWR79RgA6mvtOn3tB6wtNHOZ+q27kh+8yW41U+D0Yp2R4zt+NTBRb5U2dh9v5I5HKBxuhc8/G76mNuUbQO6CpeYYEDnwCyiYEdNMtzpPNw0e8Y2aAqwHCW8UB0bNJf7RQ8p6ZImSViK7ijoC0uJSwIH8kFgQuR5HAZygOuhm0o/tuZEubGOZm0BsFOjScho0VZBrWNJ+EVpMwmucm65gZhXGgsWJFNK19sbiK0sytUIHfuQYFc5UYK5zxPh7L/wTVA9bd9uRDNiO+TMfG5x1zikKAM/C4gc9r0laTiEynJsUxZQlc0WKyzFZNJJJ9jMWTh50KOZYLDnNFaO+2nl7hOThJXX6PSaCO5wZuCaU9wxTIodJ965NxFCLTSURq4nsUfHwo7mesK5zfUzCG+iCIQPpVLVCfizKbhOIiW5gSR3t+txS3N3wXs/cZlLHDARTs6uG3L+Vnw31TJzlvVmoeASWdpeVt1TKanybBsd8k65cd2yU7t4C5pICPP0j2QtaPaRHDmOjrKYlR5C4LN7ssdCPg0AscSzv5DfKZ83zO5sYpjDGfXKi7vswQ+1cuocb1TcyRWws/MJ0zG8SfyLimcXgI9Hk100SdIgAG/0BRzaQENDO6QL/JK54iitvllsms7E0T+QUHAUTx9d5QyRIEHIeC53lLXvzl6xBd4FctrEsp6hEgPAUxFOhmuuxKLKNAzGdmoQ5lGXPcJq8+bFNn
