apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
spec:
    encryptedData:
        cloudflare-token: AgCqlQ1dL11Wy4o0oIcI2EHke9AiYfaz+KFyu6HwiBxVJoX03nPLdttuJaPQJ3UdE8CeR888X3JM6mUIqsvEjITSgQHPn5kdh2LpkdZnVz1NWTsoixzhb7eyrAmaj+ur03H0Owdlo+NtD4GoKSXiqSRnXv4ikMljU//RymMdkMyfG5ZGuAyOHj8Gk3LzrdZ+6xEjA55trs64/T8qy29QeIIhaDQNy8isVjApot7mBsTYmeyXhvq6ExrbJte5XMvW3XmJmbNv0Cfj2NH0RVXrHGkkpvj8wnkkkYVtXZ7bNvDCNu7REipPxKCrfd2JQkadxiRhbBKrCSU+HoKaWeDq+MtXDN4lJ1ZSEc7DJ3I/6LOtZQ6RVG2kFuGpliSubDiU4o7WiwxFi/WQx8FDuDXL5f1xWD4APQZhD65ev1pais1wI9SJkTP0RKi0mSKVmkdUbttiRI2d+XXCk7ZMVrSbakjFIu/aSPgcLlWO3MDd1Ar9A7wqNzpIPHqd5Zzxxt9QiSOyOvPggP81CstBYzhj/Rg+ivX8EbroOpdrvT/J4s34ANxr69DHvQ1dcXHz+wBtCh/eNeScwhrcx29tHQZC819HBTwal6ONVsQgkux419xQWVFz+aRxk+WQ4YSW/aZc1ElyNoG1ak9jpfqcs6WuIeKJUXXRPOBd0C4aYmXvCQsRBzxEd3C+0LonfIuFWTaTUhiDsraWt7C24Po/ujA8NlajzxrcbTx6aGd55/DEHwl+KDRwxiynkBZf
