apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: investager
  namespace: investager
spec:
  chart:
    spec:
      version: ">=0.0.1"
  values:
    ui:
      domain: investager.com
      image:
        tag: main-037d56b-1675890805 # {"$imagepolicy": "flux-system:investager-ui:tag"}
