apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: system
    namespace: flux-system
spec:
    interval: 5m0s
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./system/prod
    prune: true
    wait: true
    timeout: 5m0s
