apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: flux
    namespace: flux-system
spec:
    chart:
        spec:
            version: ">=0.0.1"
    values:
        discordChannel: dev
        discordUser: flux-dev
