apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        app: react-webapp
    name: {{ .Values.application.name }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: react-webapp
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: react-webapp
        spec:
            containers:
                - image: {{ .Values.image.repository }}
                  name: webapp
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  resources: {}
                  ports:
                      - containerPort: 3001
