apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
    name: {{ .Values.application.name }}
    namespace: flux-system
spec:
    image: {{ .Values.image.repository }}
    interval: 1m0s
