apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: {{ .Values.application.name }}
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: {{ .Values.application.name }}
    filterTags:
        pattern: '^main-[a-f0-9]+-(?P<ts>[0-9]+)'
        extract: '$ts'
    policy:
        numerical:
            order: asc
