apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: {{ .Values.application.name }}
    namespace: {{ .Values.namespace }}
spec:
    entryPoints:
        - websecure
    routes:
        - match: Host(`{{ .Values.domain }}`)
          kind: Rule
          services:
            - name: {{ .Values.application.name }}
              namespace: {{ .Values.namespace }}
              port: 80
    tls:
        secretName: {{ .Values.tlsSecretName }}
