apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: {{ .Values.application.name }}-redirect
    namespace: {{ .Values.namespace }}
spec:
    redirectScheme:
        scheme: https
        permanent: true
