apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.application.name }}
    namespace: {{ .Values.namespace }}
spec:
    selector:
        name: {{ .Values.application.name }}
    ports:
        - protocol: TCP
          port: 80
          targetPort: {{ .Values.port }}
