apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: {{ .Values.application.name }}-strip
    namespace: {{ .Values.namespace }}
spec:
    stripPrefix:
        prefixes:
            - {{ .Values.application.prefix }}
