---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
    name: discord-alert
    namespace: flux-system
spec:
    providerRef:
        name: discord-provider
    eventSeverity: info
    eventSources:
        - kind: GitRepository
          name: "*"
        - kind: Kustomization
          name: "*"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
    name: discord-provider
    namespace: flux-system
spec:
    type: discord
    secretRef:
        name: discord-url
