apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: flux
    namespace: flux-system
spec:
    targetNamespace: flux-system
    releaseName: flux
    interval: 5m
    chart:
        spec:
            chart: ./charts/common/flux
            sourceRef:
                kind: GitRepository
                name: charts
                namespace: flux-system
    install:
        remediation:
            retries: 3
