apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: investager
    namespace: flux-system
spec:
    targetNamespace: investager
    releaseName: investager
    interval: 5m
    chart:
        spec:
            chart: ./charts/investager
            sourceRef:
                kind: GitRepository
                name: charts
                namespace: flux-system
    install:
        remediation:
            retries: 3
    values:
        api:
            image:
                tag: main-ffae47a-1675725095 # {"$imagepolicy": "flux-system:investager-api:tag"}
        ui:
            image:
                tag: main-ffae47a-1675725095 # {"$imagepolicy": "flux-system:investager-ui:tag"}
