apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
spec:
    encryptedData:
        cloudflare-token: AgC9hbNCq1G2WxSZR5oCf7sVtAPGcDIhmCOZTURBIp1iED/JJIKC9ZI9nTE+kNCnrveB4gqYi7XyIJ3B9NDGTXAuh0ACBkWf/1WB/HPRBwNhVgyI5snogkNgMrr5k/tuF3stpRmw+JOlCLGepQc8ZUymM2MSxp1jlyNmN7Q1OjEqiBxbLvjOQla9CegWxWPJUWITDSk7dVDd3OCHZNoVm5PcSiiLsBJVXWxu8rzdwMgMTieLG5kuztlFxoJnX1uypqEGJYENABVJRsFE3m6YTyhgI0RzniBTdorGrI6fDoCtHESZ6uYZ24LvmIaBbOZhbijJFG9KVGAzDzQovs1m8lmfZDxVmQtWzhRscyDv+4wTsuUTZzeAtSioaprbvoUF2CDdN4qW2b5ILDdrNictaIgELUAPiYJobDUHcnexzRe1N2ejL3JP7DTSpRu2CuPWtZna9Uz7dYuPmG24lArzIKa8ajOtK2UIznZy2qOWN4J25WHGakcLSjS4IiFZyHhwDQNVp2dqJaxRwc4yE8XJ8wuG5IU6zT6Amdu1rog9Y4mXNGINYbEeniHnjxb9Bua/qloAsKto6CijefZiaYzqq5fef4LNBzUni11tXv9nRNO9LqocRoJVMdasQdGIGg7yHo5y3IxYWIXvTNxmxJQG1FHcjfHf1NuezQIgB3bH1AF6lsMiQgVAPxnJc6ZshwZGMn9siPD3Qg1DXbeV3kg5Y/IrjV3vpP9G2SdwrsxRwjok1QUEOoQFMGRw
