apiVersion: v1
kind: Service
metadata:
    name: grafana
    namespace: monitoring
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: http-grafana
    selector:
        app: grafana
    sessionAffinity: None
