dependencies:
    - alias: api
      name: investager-api
      version: "0.1.9"
      repository: file://../common/frontend
    - alias: ui
      name: investager-ui
      version: "0.1.9"
      repository: file://../common/frontend
apiVersion: v2
name: investager
description: Investager Helm chart
type: application
version: 0.1.10
appVersion: "0.1.10"
