apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: grafana-cert
    namespace: monitoring
spec:
    secretName: grafana-tls
    issuerRef:
        name: letsencrypt
        kind: ClusterIssuer
    commonName: "grafana.investager.com"
    dnsNames:
        - "grafana.investager.com"
