apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: investager-ui
spec:
    chart:
        spec:
            version: '>=0.0.1'
# values:
#     ingress:
#         hosts:
#             - host: investager.dev
#               paths:
#                   - path: /
#                     pathType: ImplementationSpecific
