---
apiVersion: v1
kind: Namespace
metadata:
    name: longhorn-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: longhorn
    namespace: longhorn-system
spec:
    targetNamespace: longhorn-system
    releaseName: longhorn
    chart:
        spec:
            chart: longhorn
            sourceRef:
                kind: HelmRepository
                name: longhorn-charts
                namespace: flux-system
            version: "1.4.0"
    interval: 1h0m0s
    values:
        ingress:
            enabled: true
            host: longhorn.local.investager.com
        longhornUI:
            replicas: 1
        longhornConversionWebhook:
            replicas: 1
        longhornAdmissionWebhook:
            replicas: 1
        longhornRecoveryBackend:
            replicas: 1
    install:
        crds: CreateReplace
    upgrade:
        crds: CreateReplace
