apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
    name: discord-provider
    namespace: flux-system
spec:
    type: discord
    channel: {{ .Values.discordChannel }}
    username: {{ .Values.discordUser }}
    secretRef:
        name: discord-url
