---
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: postgres
    namespace: postgres
spec:
    targetNamespace: postgres
    releaseName: postgres
    chart:
        spec:
            chart: postgresql
            version: "12.2.1"
            sourceRef:
                kind: HelmRepository
                name: bitnami
                namespace: flux-system
    interval: 1h0m0s
    install:
        remediation:
            retries: 3
    values:
        global:
            storageClass: longhorn
        # auth:
        #     existingSecret: postgres
        #   secretKeys:
        #       adminPasswordKey: admin
        #       userPasswordKey: user
        architecture: standalone
