apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
    - ../base/flux
    - ../base/jetstack
    - ../base/longhorn
patchesStrategicMerge:
    - flux-values.yaml
