apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: grafana-ingress
    namespace: monitoring
spec:
    entryPoints:
        - websecure
    routes:
        - match: Host(`replace-me`)
          kind: Rule
          services:
              - name: grafana
                namespace: monitoring
                port: 80
                # sticky:
                #     cookie:
                #         httpOnly: true
                #         name: grafana
                #         secure: true
                #         sameSite: none
    tls:
        secretName: grafana-tls
