apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: grafana-ingress
    namespace: monitoring
spec:
    entryPoints:
        - websecure
    tls:
        secretName: grafana-tls
