apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
    - grafana-certificate.yaml
    - grafana-ingress.yaml
    - namespace.yaml
    - prometheus-release.yaml
