apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: loki
    namespace: monitoring
spec:
    targetNamespace: monitoring
    releaseName: loki
    chart:
        spec:
            chart: loki-stack
            version: "2.9.9"
            sourceRef:
                kind: HelmRepository
                name: grafana
                namespace: flux-system
    interval: 1h0m0s
    install:
        remediation:
            retries: 3
    values:
        grafana:
            enabled: false
        prometheus:
            enabled: false
