apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: prometheus
    namespace: monitoring
spec:
    targetNamespace: monitoring
    releaseName: prometheus
    chart:
        spec:
            chart: kube-prometheus-stack
            version: "45.0.0"
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: flux-system
    interval: 1h0m0s
    install:
        remediation:
            retries: 3
    values:
        fullnameOverride: prometheus
        alertmanager:
            fullnameOverride: alertmanager
            enabled: true
            ingress:
                enabled: false
        grafana:
            fullnameOverride: grafana
            serviceMonitor:
                enabled: true
            admin:
                existingSecret: grafana
                userKey: username
                passwordKey: password
            additionalDataSources:
                - name: Loki
                  type: loki
                  access: proxy
                  url: http://loki.monitoring:3100/
                  jsonData:
                      maxLines: 1000
                - name: Prometheus
                  type: prometheus
                  uid: prometheus
                  access: proxy
                  url: http://prometheus-prometheus.monitoring:9090/
        nodeExporter:
            enabled: false
        prometheus:
            enabled: true
            prometheusSpec:
                replicas: 1
                replicaExternalLabelName: "replica"
                ruleSelectorNilUsesHelmValues: false
                serviceMonitorSelectorNilUsesHelmValues: false
                podMonitorSelectorNilUsesHelmValues: false
                probeSelectorNilUsesHelmValues: false
                retention: 48h
                enableAdminAPI: true
                walCompression: true
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: local-path
                            accessModes:
                                [
                                    "ReadWriteOnce",
                                ]
                            resources:
                                requests:
                                    storage: 10Gi
        prometheus-node-exporter:
            fullnameOverride: node-exporter
        thanosRuler:
            enabled: false
