apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: {{ .Values.namespace }}
    name: {{ .Values.application.name }}
    labels:
        app: next-app
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: next-app
    template:
        metadata:
            labels:
                app: next-app
                name: {{ .Values.application.name }}
        spec:
            containers:
                - image: {{ .Values.image.repository }}
                  name: next
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  ports:
                      - containerPort: 3001
