apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: longhorn-cert
    namespace: longhorn
spec:
    secretName: longhorn-tls
    issuerRef:
        name: letsencrypt
        kind: ClusterIssuer
    commonName: "longhorn.local.investager.com"
    dnsNames:
        - "longhorn.local.investager.com"
