apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: longhorn-auth
    namespace: longhorn-system
spec:
    encryptedData:
        users: AgBaaA/hsaKrBLC4nLu9Dl0hpiJXrWUH5c95ykv2V/nxvsWQ6pZ3g0neeHttH6mr1/7drrU3KlENtvNwNxSMkLn1H21U0brVcb/suJba/F+CzxkEPaDRaUp2CQ0GTifkLUKNhQZ2PxitWnqjAajpWQHSpsw8WAfHc84LvlSNzzh7s575lQ3o7uQPsYHI58EVsXd8jjq+QuYIohT0R4q1Kav0g9wMI7YYlrKNl35cqb323NkVvDVimqOdMCNChuBEI0+tDz/BdOVC6+aNK17hE3X59VmTykluQjdGxo+L8vCoEHkn5YUYEwLf5YWEmUkzkO7hXSRcJhxJB5w0YfrkbuB+F/c5Lrvl0TC4d+QJ62ZFSLgYHDJsm9NhpKLs4SvLgsH3f4Mc4T4ZgUGraVl1DKg492Rykgdo00mLC2sMfvg6meNY8t6v/IzgHmymuvFSxLYYt0mrQJvwff46M0kFIzPsQ1SlJq7WXatX26+mgnqKzAsD2E3e74Ea94jD7b3ulg9oQUA5k6VutdIQQH4loQcIwOO1evOv6PZH56Yj/pGMOhELZDWfU4dqoY8JLewSWBXCyh2ZjkxLktH3IrsntggFGe9dawRuxp6V/hkvQnsPGvPkZ017mFyaKId7LVDw4uiHCXFr8X/PmXL38jMpGRaBK77JvSWuQGoopH4asDmhdCYDHegTRQR7+2UYJdTcVH8bBwVjJundLpbWFoCBBzVs8/m+hOfNuTo9ok6/S+mg2R+Fbgf5SOTL8ciTdFxe
