apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: longhorn
    namespace: longhorn-system
spec:
    entryPoints:
        - websecure
    tls:
        secretName: longhorn-tls
    routes:
        - match: Host(`longhorn.local.investager.com`)
          kind: Rule
          middlewares:
              - name: longhorn-auth
                namespace: longhorn-system
          services:
              - name: longhorn-frontend
                namespace: longhorn-system
                port: 80
